/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as windowsRouteBRouteImport } from './routes/(windows)/routeB'
import { Route as windowsRouteARouteImport } from './routes/(windows)/routeA'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const windowsRouteBRoute = windowsRouteBRouteImport.update({
  id: '/(windows)/routeB',
  path: '/routeB',
  getParentRoute: () => rootRouteImport,
} as any)
const windowsRouteARoute = windowsRouteARouteImport.update({
  id: '/(windows)/routeA',
  path: '/routeA',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/routeA': typeof windowsRouteARoute
  '/routeB': typeof windowsRouteBRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/routeA': typeof windowsRouteARoute
  '/routeB': typeof windowsRouteBRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(windows)/routeA': typeof windowsRouteARoute
  '/(windows)/routeB': typeof windowsRouteBRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/routeA' | '/routeB'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/routeA' | '/routeB'
  id: '__root__' | '/' | '/(windows)/routeA' | '/(windows)/routeB'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  windowsRouteARoute: typeof windowsRouteARoute
  windowsRouteBRoute: typeof windowsRouteBRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(windows)/routeB': {
      id: '/(windows)/routeB'
      path: '/routeB'
      fullPath: '/routeB'
      preLoaderRoute: typeof windowsRouteBRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(windows)/routeA': {
      id: '/(windows)/routeA'
      path: '/routeA'
      fullPath: '/routeA'
      preLoaderRoute: typeof windowsRouteARouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  windowsRouteARoute: windowsRouteARoute,
  windowsRouteBRoute: windowsRouteBRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
